### ISSUE TITLE
第三步中的更精确的设定圆的位置和半径

### ISSUE THREAD

**Issue by fentouxungui** [Xingyinliu-Lab/DVT#1]
我看教程中，第三步圆的设定是参考的第二步的，这个是人为设定的，这个圆如果稍大些不会影响UMATracker的Tracking，但是第三步中圆的设定是很关键的，如果设大了，会影响arena dege和arena centre，个人建议使用UMATracker得到的Tracking结果来计算圆的圆心和半径。这只是我的一个想法，具体实现代码是没有的~

**Comment by Xingyinliu-Lab** [comment]
我们考虑过这种思路，使用tracking结果计算边界的困难在于，我们无法保证所有视频中果蝇会探索边界，这使得计算获得的圆心、半径和实际的差距会更大。 现在采用的方案是根据视频图片标记边界位置，为了提高结果准确性，我们不需要用户直接去标记圆心，而是标记圆周上的三个点，这显然比标记圆心更加方便和准确。当然手动标记依然可能存在误差，它可能在这个视频中测量的半径偏小，也可能在下个视频中测量的圆半径偏大，是一种波动的偏差，这种误差与正常的仪器测量偏差一样，是可以接受的。
